-- MedicsPro Library V1: curated platform-owned assessment content only.
BEGIN;

INSERT INTO public.assessment_templates (id, clinic_id, owner_type, name, description, specialty, status, created_by)
VALUES
 ('10000000-0000-4000-8000-000000000003', NULL, 'platform', 'Anamnese Médica Geral', 'Anamnese MedicsPro para consulta médica geral, organizada por seções e respostas estruturadas.', 'medicina geral', 'active', NULL),
 ('10000000-0000-4000-8000-000000000004', NULL, 'platform', 'Anamnese Psiquiátrica', 'Anamnese MedicsPro para avaliação psiquiátrica, sem scoring ou inferência diagnóstica automática.', 'psiquiatria', 'active', NULL)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.assessment_template_versions (id, template_id, version, schema, published_at, published_by)
VALUES
 ('11000000-0000-4000-8000-000000000003','10000000-0000-4000-8000-000000000003',1,
  '{"sections":[
   {"key":"demanda","title":"Demanda atual","components":[{"key":"queixa_principal","type":"long_text","label":"Queixa principal / motivo da consulta","required":true},{"key":"historia_atual","type":"long_text","label":"História do problema atual","required":true},{"key":"inicio","type":"single_choice","label":"Início dos sintomas","config":{"options":["Agudo","Subagudo","Crônico","Não informado"]}},{"key":"evolucao","type":"single_choice","label":"Evolução percebida","config":{"options":["Melhorando","Estável","Piorando","Flutuante"]}},{"key":"sintomas_associados","type":"multiple_choice","label":"Sintomas associados","config":{"options":["Febre","Fadiga","Náusea/vômito","Tontura","Dispneia","Nenhum","Outro"]}},{"key":"dor_presente","type":"yes_no","label":"Há dor relevante?"},{"key":"intensidade_dor","type":"scale","label":"Intensidade da dor (0–10)","config":{"min":0,"max":10}}]},
   {"key":"antecedentes","title":"Antecedentes e segurança clínica","components":[{"key":"antecedentes_pessoais","type":"long_text","label":"Antecedentes pessoais relevantes"},{"key":"cirurgias_procedimentos","type":"long_text","label":"Cirurgias ou procedimentos relevantes"},{"key":"antecedentes_familiares","type":"long_text","label":"Antecedentes familiares relevantes"},{"key":"medicamentos_snapshot","type":"long_text","label":"Medicamentos referidos nesta consulta","helpText":"Registro contextual; não substitui a fonte canônica de prescrições."},{"key":"alergias_snapshot","type":"long_text","label":"Alergias referidas nesta consulta","helpText":"Registro contextual; confirmar e manter no cadastro clínico canônico quando disponível."}]},
   {"key":"habitos","title":"Hábitos e repercussão","components":[{"key":"tabagismo","type":"single_choice","label":"Tabagismo","config":{"options":["Nunca","Atual","Prévio","Não informado"]}},{"key":"alcool","type":"single_choice","label":"Uso de álcool","config":{"options":["Não refere","Ocasional","Regular","Prejudicial percebido","Não informado"]}},{"key":"outras_substancias","type":"yes_no","label":"Refere uso de outras substâncias?"},{"key":"sono","type":"single_choice","label":"Sono","config":{"options":["Preservado","Sono insuficiente","Sono não reparador","Insônia","Outro"]}},{"key":"atividade_fisica","type":"single_choice","label":"Atividade física","config":{"options":["Regular","Ocasional","Não realiza","Não informado"]}},{"key":"impacto_funcional","type":"long_text","label":"Repercussão funcional, social ou ocupacional"}]},
   {"key":"revisao_sintese","title":"Revisão e síntese","components":[{"key":"revisao_clinica","type":"multiple_choice","label":"Sistemas com sintomas relevantes","config":{"options":["Cardiovascular","Respiratório","Gastrointestinal","Neurológico","Urinário","Musculoesquelético","Pele","Nenhum"]}},{"key":"observacoes","type":"long_text","label":"Observações clínicas"},{"key":"sintese_clinica","type":"long_text","label":"Síntese clínica","required":true}]}
  ]}'::jsonb, now(), NULL),
 ('11000000-0000-4000-8000-000000000004','10000000-0000-4000-8000-000000000004',1,
  '{"sections":[
   {"key":"demanda_evolucao","title":"Demanda e evolução","components":[{"key":"motivo_consulta","type":"long_text","label":"Motivo da consulta","required":true},{"key":"origem_demanda","type":"single_choice","label":"Origem da demanda","config":{"options":["Espontânea","Encaminhamento","Família/rede","Outro"]}},{"key":"evolucao_temporal","type":"long_text","label":"Instalação, duração e evolução"},{"key":"episodios_previos","type":"yes_no","label":"Há episódios prévios semelhantes?"},{"key":"fatores_precipitantes","type":"long_text","label":"Fatores precipitantes percebidos"},{"key":"impacto_funcional","type":"long_text","label":"Impacto funcional, social ou ocupacional","required":true}]},
   {"key":"sintomas_atuais","title":"Sintomas atuais","components":[{"key":"humor","type":"single_choice","label":"Humor predominante","config":{"options":["Eutímico","Triste","Irritável","Lábil","Ansioso","Outro"]}},{"key":"anedonia","type":"yes_no","label":"Refere redução de interesse ou prazer?"},{"key":"ansiedade","type":"scale","label":"Intensidade subjetiva de ansiedade (0–10)","config":{"min":0,"max":10}},{"key":"energia","type":"single_choice","label":"Energia","config":{"options":["Preservada","Reduzida","Aumentada","Oscilante"]}},{"key":"concentracao","type":"single_choice","label":"Concentração","config":{"options":["Preservada","Reduzida","Oscilante"]}},{"key":"psicomotricidade","type":"single_choice","label":"Psicomotricidade observada/referida","config":{"options":["Sem alteração evidente","Lentificação","Agitação","Outro"]}},{"key":"sono_apetite","type":"multiple_choice","label":"Sono e apetite","config":{"options":["Sono preservado","Insônia","Hipersonia","Apetite preservado","Apetite reduzido","Apetite aumentado"]}},{"key":"sintomas_somaticos","type":"long_text","label":"Sintomas somáticos relevantes"}]},
   {"key":"antecedentes_tratamentos","title":"Antecedentes e tratamentos","components":[{"key":"antecedentes_psiquiatricos","type":"long_text","label":"Antecedentes psiquiátricos relevantes"},{"key":"psicoterapia_previa","type":"single_choice","label":"Psicoterapia prévia/atual","config":{"options":["Atual","Prévia","Nunca","Não informado"]}},{"key":"internacoes","type":"single_choice","label":"Internações psiquiátricas","config":{"options":["Não refere","Uma","Mais de uma","Não informado"]}},{"key":"psicofarmacos_snapshot","type":"long_text","label":"Psicofármacos referidos nesta consulta","helpText":"Contexto da entrevista; não substitui a fonte canônica de prescrições."},{"key":"antecedentes_medicos","type":"long_text","label":"Antecedentes médicos relevantes"},{"key":"familia_psiquiatria","type":"long_text","label":"Antecedentes familiares relevantes"}]},
   {"key":"contexto_risco","title":"Contexto, substâncias e risco","components":[{"key":"alcool_tabaco_substancias","type":"multiple_choice","label":"Uso de substâncias referido","config":{"options":["Álcool","Tabaco","Outras substâncias","Não refere","Não informado"]}},{"key":"contexto_psicossocial","type":"long_text","label":"Contexto psicossocial e rede de apoio"},{"key":"risco_atual","type":"long_text","label":"Avaliação clínica contextual de risco","required":true,"helpText":"Registre ideação, planejamento, fatores de proteção, rede e julgamento clínico. Não produz score ou classificação automática."}]},
   {"key":"exame_sintese","title":"Exame do estado mental e síntese","components":[{"key":"estado_mental","type":"long_text","label":"Exame do estado mental"},{"key":"observacoes","type":"long_text","label":"Observações clínicas"},{"key":"sintese_clinica","type":"long_text","label":"Síntese clínica","required":true}]}
  ]}'::jsonb, now(), NULL)
ON CONFLICT (id) DO NOTHING;

COMMIT;
