export const NEXUS_ANTIDEPRESSANT_SWITCH_RULE_VERSION = 'nexus-antidepressant-switch-2026-09-04';

export type AntidepressantClass = 'ISRS' | 'ISRN' | 'Atípico / Modulador' | 'Tricíclico' | 'IMAO' | 'Outro';
export type DiscontinuationRisk = 'Baixo' | 'Moderado' | 'Alto' | 'Muito Alto';

export interface AntidepressantInfo {
  id: string;
  name: string;
  class: AntidepressantClass;
  standardDoses: number[];
  minTherapeuticDose: number;
  maxRecommendedDose: number;
  hayasakaEqToFluoxetine40: number;
  isRctEvidence: boolean;
  halfLifeHours: string;
  activeMetaboliteHalfLife?: string;
  cypInteractions: Record<string, string>;
  discontinuationRisk: DiscontinuationRisk;
  serotoninRisk: 'Moderado' | 'Alto' | 'Muito Alto' | 'Muito Alto (IMAO)';
  specialAlerts: string[];
}

export const ANTIDEPRESSANTS_DB: Record<string, AntidepressantInfo> = {
  fluoxetina: { id:'fluoxetina', name:'Fluoxetina', class:'ISRS', standardDoses:[10,20,40,60,80], minTherapeuticDose:20, maxRecommendedDose:80, hayasakaEqToFluoxetine40:40, isRctEvidence:true, halfLifeHours:'48 - 72h (2-3 dias)', activeMetaboliteHalfLife:'Norfluoxetina: 168 - 360h (7-15 dias)', cypInteractions:{cyp2D6:'Potente',cyp2C19:'Moderado',cyp3A4:'Fraco'}, discontinuationRisk:'Baixo', serotoninRisk:'Alto', specialAlerts:['Meia-vida plasmática ultralonga da norfluoxetina (~1 a 2 semanas): "auto-desmame" biológico natural.','Inibidor potente do CYP2D6.','Obrigatório aguardar 5 semanas (35 dias) de washout estrito caso a troca seja direcionada para IMAO (Tranilcipromina).'] },
  sertralina: { id:'sertralina', name:'Sertralina', class:'ISRS', standardDoses:[25,50,100,150,200], minTherapeuticDose:50, maxRecommendedDose:200, hayasakaEqToFluoxetine40:98.5, isRctEvidence:true, halfLifeHours:'26h', activeMetaboliteHalfLife:'N-desmetilsertralina: 62 - 104h (pouca atividade)', cypInteractions:{cyp2D6:'Fraco (moderado em doses >150mg)',cyp2C19:'Fraco',cyp3A4:'Fraco'}, discontinuationRisk:'Moderado', serotoninRisk:'Alto', specialAlerts:['Perfil de segurança cardiovascular favorável (estudos SADHART / ENRICHD).','Leve ação inibidora da recaptação de dopamina em doses elevadas (>150mg/dia).','Baixo potencial de interações farmacocinéticas comparada a Fluoxetina e Paroxetina.'] },
  escitalopram: { id:'escitalopram', name:'Escitalopram', class:'ISRS', standardDoses:[5,10,15,20], minTherapeuticDose:10, maxRecommendedDose:20, hayasakaEqToFluoxetine40:18, isRctEvidence:true, halfLifeHours:'27 - 32h', cypInteractions:{cyp2D6:'Fraco',cyp2C19:'Substrato',cyp3A4:'Substrato'}, discontinuationRisk:'Moderado', serotoninRisk:'Alto', specialAlerts:['ISRS mais seletivo para o transportador SERT.','Risco dose-dependente de prolongamento do intervalo QTc.','Perfil límpido de interações metabólicas CYP450.'] },
  citalopram: { id:'citalopram', name:'Citalopram', class:'ISRS', standardDoses:[10,20,30,40], minTherapeuticDose:20, maxRecommendedDose:40, hayasakaEqToFluoxetine40:36.6, isRctEvidence:true, halfLifeHours:'35h', cypInteractions:{cyp2C19:'Substrato',cyp2D6:'Fraco',cyp3A4:'Substrato'}, discontinuationRisk:'Moderado', serotoninRisk:'Alto', specialAlerts:['Alerta FDA/Anvisa de prolongamento de QTc e risco de Torsades de Pointes: dose teto de 40 mg/dia (20 mg/dia para idosos).'] },
  paroxetina: { id:'paroxetina', name:'Paroxetina', class:'ISRS', standardDoses:[10,20,30,40,50,60], minTherapeuticDose:20, maxRecommendedDose:60, hayasakaEqToFluoxetine40:34, isRctEvidence:true, halfLifeHours:'21 - 24h', cypInteractions:{cyp2D6:'Potente (inibe sua própria eliminação)',cyp1A2:'Fraco',cyp3A4:'Fraco'}, discontinuationRisk:'Muito Alto', serotoninRisk:'Alto', specialAlerts:['Altíssimo risco de Síndrome de Descontinuação. Exige desmame extremamente lento.','Efeito anticolinérgico intrínseco.','Inibidor potente de CYP2D6.'] },
  fluvoxamina: { id:'fluvoxamina', name:'Fluvoxamina', class:'ISRS', standardDoses:[50,100,150,200,300], minTherapeuticDose:100, maxRecommendedDose:300, hayasakaEqToFluoxetine40:143.3, isRctEvidence:true, halfLifeHours:'15 - 20h', cypInteractions:{cyp1A2:'Potente',cyp2C19:'Potente',cyp2C9:'Moderado',cyp3A4:'Moderado',cyp2D6:'Fraco'}, discontinuationRisk:'Alto', serotoninRisk:'Alto', specialAlerts:['Inibidor potente do CYP1A2 e CYP2C19.','Potente afinidade com receptores Sigma-1.'] },
  venlafaxina: { id:'venlafaxina', name:'Venlafaxina (XR)', class:'ISRN', standardDoses:[37.5,75,150,225,300], minTherapeuticDose:75, maxRecommendedDose:300, hayasakaEqToFluoxetine40:146.5, isRctEvidence:true, halfLifeHours:'5h', activeMetaboliteHalfLife:'O-desmetilvenlafaxina: 11h', cypInteractions:{cyp2D6:'Substrato (fraco inibidor em altas doses)',cyp3A4:'Substrato'}, discontinuationRisk:'Muito Alto', serotoninRisk:'Alto', specialAlerts:['Ação predominantemente serotoninérgica em doses <150mg/dia; bloqueio noradrenérgico robusto a partir de ≥150mg/dia.','Elevadíssimo risco de síndrome de descontinuação abrupta.','Monitorar pressão arterial sistêmica e frequência cardíaca em doses elevadas.'] },
  desvenlafaxina: { id:'desvenlafaxina', name:'Desvenlafaxina', class:'ISRN', standardDoses:[50,100,150], minTherapeuticDose:50, maxRecommendedDose:150, hayasakaEqToFluoxetine40:90, isRctEvidence:false, halfLifeHours:'11h', cypInteractions:{cyp2D6:'Fraco',cyp3A4:'Mínimo'}, discontinuationRisk:'Alto', serotoninRisk:'Alto', specialAlerts:['Metabólito ativo direto da venlafaxina.','Dose terapêutica padrão inicia em 50 mg/dia.'] },
  duloxetina: { id:'duloxetina', name:'Duloxetina', class:'ISRN', standardDoses:[30,60,90,120], minTherapeuticDose:60, maxRecommendedDose:120, hayasakaEqToFluoxetine40:75, isRctEvidence:false, halfLifeHours:'12h', cypInteractions:{cyp2D6:'Moderado',cyp1A2:'Substrato'}, discontinuationRisk:'Alto', serotoninRisk:'Alto', specialAlerts:['Duplo bloqueio 5-HT e NA equilibrado desde a dose inicial.','Inibidor moderado do CYP2D6.','Evitar em insuficiência hepática ou consumo crônico de álcool.'] },
  bupropiona: { id:'bupropiona', name:'Bupropiona (XL/SR)', class:'Atípico / Modulador', standardDoses:[150,300,450], minTherapeuticDose:150, maxRecommendedDose:450, hayasakaEqToFluoxetine40:300, isRctEvidence:false, halfLifeHours:'14 - 21h', activeMetaboliteHalfLife:'Hidroxibupropiona: 20 - 37h', cypInteractions:{cyp2D6:'Potente',cyp2B6:'Substrato'}, discontinuationRisk:'Baixo', serotoninRisk:'Moderado', specialAlerts:['Inibidor da recaptação de Dopamina e Noradrenalina (IRDN).','Inibidor potente do CYP2D6.','Contraindicado formalmente em histórico de convulsões, bulimia/anorexia e desmame abrupto de álcool ou benzodiazepínicos.'] },
  mirtazapina: { id:'mirtazapina', name:'Mirtazapina', class:'Atípico / Modulador', standardDoses:[15,30,45], minTherapeuticDose:15, maxRecommendedDose:45, hayasakaEqToFluoxetine40:50.9, isRctEvidence:true, halfLifeHours:'20 - 40h', cypInteractions:{cyp1A2:'Substrato',cyp2D6:'Substrato',cyp3A4:'Substrato'}, discontinuationRisk:'Moderado', serotoninRisk:'Alto', specialAlerts:['Antagonista alfa-2 adrenérgico pré-sináptico e bloqueador 5-HT2 / 5-HT3 e H1.','Sedação acentuada e apetite aumentado, especialmente em doses baixas.','Quase nulo potencial de indução ou inibição enzimática no citocromo P450.'] },
  vortioxetina: { id:'vortioxetina', name:'Vortioxetina', class:'Atípico / Modulador', standardDoses:[5,10,15,20], minTherapeuticDose:10, maxRecommendedDose:20, hayasakaEqToFluoxetine40:20, isRctEvidence:false, halfLifeHours:'66h', cypInteractions:{cyp2D6:'Substrato principal',cyp3A4:'Substrato menor'}, discontinuationRisk:'Baixo', serotoninRisk:'Alto', specialAlerts:['Antidepressivo multimodal.','Excelente perfil de tolerabilidade cognitiva e menor taxa de disfunção sexual.','Se associada a inibidores potentes de CYP2D6, reduzir dose pela metade.'] },
  trazodona: { id:'trazodona', name:'Trazodona', class:'Atípico / Modulador', standardDoses:[50,100,150,300], minTherapeuticDose:150, maxRecommendedDose:300, hayasakaEqToFluoxetine40:300, isRctEvidence:false, halfLifeHours:'7 - 13h', cypInteractions:{cyp3A4:'Substrato',cyp2D6:'Substrato menor'}, discontinuationRisk:'Baixo', serotoninRisk:'Alto', specialAlerts:['Antagonista e Inibidor de Recaptação de Serotonina (SARI).','Doses baixas atuam primariamente como sedativo/hipnótico.','Efeito antidepressivo clínico requer doses de 150 a 300 mg/dia.','Risco de hipotensão ortostática e priapismo.'] },
  amitriptilina: { id:'amitriptilina', name:'Amitriptilina', class:'Tricíclico', standardDoses:[25,50,75,100,150], minTherapeuticDose:75, maxRecommendedDose:150, hayasakaEqToFluoxetine40:122.3, isRctEvidence:true, halfLifeHours:'15 - 30h', activeMetaboliteHalfLife:'Nortriptilina: 20 - 40h', cypInteractions:{cyp2D6:'Substrato principal',cyp2C19:'Substrato principal',cyp1A2:'Substrato'}, discontinuationRisk:'Alto', serotoninRisk:'Alto', specialAlerts:['Forte carga anticolinérgica, anti-histamínica e alfa-1.','Risco de toxicidade cardíaca e letalidade em overdose; solicitar ECG prévio em cardiopatas e idosos.','Níveis séricos aumentam com inibidores de CYP2D6.'] },
  nortriptilina: { id:'nortriptilina', name:'Nortriptilina', class:'Tricíclico', standardDoses:[25,50,75,100], minTherapeuticDose:50, maxRecommendedDose:100, hayasakaEqToFluoxetine40:75, isRctEvidence:false, halfLifeHours:'20 - 40h', cypInteractions:{cyp2D6:'Substrato principal'}, discontinuationRisk:'Alto', serotoninRisk:'Alto', specialAlerts:['Janela terapêutica plasmática bem estabelecida (50 - 150 ng/mL).','Menor efeito hipotensor postural e menor carga anticolinérgica que a Amitriptilina.'] },
  clomipramina: { id:'clomipramina', name:'Clomipramina', class:'Tricíclico', standardDoses:[25,75,150,225], minTherapeuticDose:75, maxRecommendedDose:225, hayasakaEqToFluoxetine40:116.1, isRctEvidence:true, halfLifeHours:'20 - 32h', activeMetaboliteHalfLife:'Desmetilclomipramina: 36 - 60h', cypInteractions:{cyp2D6:'Substrato / Inibidor moderado',cyp1A2:'Substrato',cyp2C19:'Substrato'}, discontinuationRisk:'Alto', serotoninRisk:'Muito Alto', specialAlerts:['Tricíclico com potente ação inibidora de recaptação de serotonina.','Alto risco de síndrome serotoninérgica em associações e maior potencial convulsivógeno entre os tricíclicos.'] },
  tranilcipromina: { id:'tranilcipromina', name:'Tranilcipromina (Parnate)', class:'IMAO', standardDoses:[10,20,30,40], minTherapeuticDose:20, maxRecommendedDose:60, hayasakaEqToFluoxetine40:25, isRctEvidence:false, halfLifeHours:'2h (mas inibição enzimática irreversível dura 14 dias)', cypInteractions:{cyp2C19:'Inibidor',cyp2A6:'Inibidor'}, discontinuationRisk:'Muito Alto', serotoninRisk:'Muito Alto (IMAO)', specialAlerts:['IMAO Irreversível e Não-Seletivo.','RISCO CRÍTICO: requer dieta estrita com restrição de Tiramina.','WASHOUT OBRIGATÓRIO: 14 dias após outros antidepressivos, 5 semanas após Fluoxetina; 14 dias após Tranilcipromina antes de qualquer outro antidepressivo.'] },
  moclobemida: { id:'moclobemida', name:'Moclobemida (Aurorix)', class:'IMAO', standardDoses:[150,300,600], minTherapeuticDose:300, maxRecommendedDose:600, hayasakaEqToFluoxetine40:300, isRctEvidence:false, halfLifeHours:'2 - 4h (RIMA reversível)', cypInteractions:{cyp2C19:'Inibidor',cyp2D6:'Inibidor moderado'}, discontinuationRisk:'Moderado', serotoninRisk:'Alto', specialAlerts:['Inibidor Reversível da MAO-A (RIMA).','Washout mais curto necessário (24 a 48 horas) em comparação aos IMAOs irreversíveis.'] },
};

export interface TransitionStep { stepNumber:number; periodLabel:string; sourceDose:string; targetDose:string; clinicalAction:string; symptomsToMonitor:string; }
export interface AntidepressantSwitchPlan {
  sourceDrug: AntidepressantInfo; sourceDoseMg:number; targetDrug:AntidepressantInfo;
  calculatedEquivalentDoseMg:number; recommendedStartingDoseMg:number; recommendedTargetDoseMg:number;
  evidenceSource:'Hayasaka et al., 2015 (Meta-análise de RCTs)'|'Consenso Clínico Especializado (Maudsley / APA / CANMAT)';
  strategyType:'direct'|'cross_taper'|'washout'; strategyTitle:string; strategySummary:string; durationWeeks:number;
  timelineSteps:TransitionStep[]; pharmacologicalRationale:string[];
  clinicalRisks:{ serotoninSyndrome:{risk:'Baixo'|'Moderado'|'Alto'|'Crítico';note:string}; discontinuationSyndrome:{risk:DiscontinuationRisk;note:string}; cypInteractions:string[]; cardiacAndOtherAlerts:string[] };
  patientInstructions:string[]; soapPrescriptionText:string;
}

function nearestDose(target: AntidepressantInfo, raw: number) {
  return target.standardDoses.reduce((best, dose) => Math.abs(dose-raw) < Math.abs(best-raw) ? dose : best, target.standardDoses[0]);
}

export function calculateAntidepressantTransition(sourceDrugId:string, sourceDoseMg:number, targetDrugId:string):AntidepressantSwitchPlan {
  const source=ANTIDEPRESSANTS_DB[sourceDrugId]; const target=ANTIDEPRESSANTS_DB[targetDrugId];
  if (!source || !target) throw new Error('Antidepressivo inválido.');
  if (!Number.isFinite(sourceDoseMg) || sourceDoseMg<=0) throw new Error('Dose atual inválida.');
  const raw=(sourceDoseMg/source.hayasakaEqToFluoxetine40)*target.hayasakaEqToFluoxetine40;
  const targetDose=nearestDose(target,raw); const initialDose=Math.min(target.minTherapeuticDose,targetDose);
  const evidenceSource=source.isRctEvidence&&target.isRctEvidence?'Hayasaka et al., 2015 (Meta-análise de RCTs)':'Consenso Clínico Especializado (Maudsley / APA / CANMAT)';
  let strategyType:'direct'|'cross_taper'|'washout'='cross_taper'; let strategyTitle='Troca Cruzada Gradual em 3 Semanas'; let strategySummary=''; let durationWeeks=3; const timelineSteps:TransitionStep[]=[];
  if(source.class==='IMAO'||target.class==='IMAO'){
    strategyType='washout'; strategyTitle='Troca com Janela de Descontinuação Obrigatória (Intervalo Livre de Fármacos)';
    if(source.id==='fluoxetina'&&target.id==='tranilcipromina'){
      durationWeeks=6; strategySummary='Devido à meia-vida prolongada da Fluoxetina e Norfluoxetina, é OBRIGATÓRIO aguardar 5 semanas (35 dias) de intervalo livre completo.';
      timelineSteps.push({stepNumber:1,periodLabel:'Semana 1 (Dias 1 - 7)',sourceDose:`${source.name} ${Math.round(sourceDoseMg/2)} mg/dia`,targetDose:'NENHUMA',clinicalAction:'Reduzir a dose de Fluoxetina pela metade.',symptomsToMonitor:'Estabilidade emocional e sintomas depressivos residuais.'},{stepNumber:2,periodLabel:'Semanas 2 a 6 (5 semanas de intervalo livre)',sourceDose:'SUSPENSA TOTALMENTE',targetDose:'NÃO INICIAR AINDA',clinicalAction:'Aguardar 5 semanas completas sem antidepressivo.',symptomsToMonitor:'Acompanhamento semanal.'},{stepNumber:3,periodLabel:'Semana 7 em diante',sourceDose:'SUSPENSA DEFINITIVAMENTE',targetDose:`${target.name} 10 mg/dia`,clinicalAction:'Iniciar em dose baixa com restrição de tiramina.',symptomsToMonitor:'Pressão arterial e adesão alimentar.'});
    } else if(source.class!=='IMAO'&&target.id==='tranilcipromina'){
      durationWeeks=4; strategySummary='Suspender gradualmente e aguardar 14 dias de intervalo livre absoluto antes da Tranilcipromina.';
      timelineSteps.push({stepNumber:1,periodLabel:'Semana 1',sourceDose:`${source.name} ${Math.round(sourceDoseMg/2)} mg/dia`,targetDose:'NENHUMA',clinicalAction:'Redução de 50% da dose.',symptomsToMonitor:'Sintomas de descontinuação.'},{stepNumber:2,periodLabel:'Semanas 2 e 3',sourceDose:'SUSPENSO TOTALMENTE',targetDose:'NÃO INICIAR AINDA',clinicalAction:'14 dias de intervalo livre.',symptomsToMonitor:'Monitoramento semanal de humor.'},{stepNumber:3,periodLabel:'Semana 4',sourceDose:'SUSPENSO DEFINITIVAMENTE',targetDose:`${target.name} 10 mg/dia`,clinicalAction:'Introduzir após janela obrigatória.',symptomsToMonitor:'PA ortostática e cefaleia.'});
    } else if(source.id==='tranilcipromina'){
      durationWeeks=3; strategySummary='A inibição da MAO é irreversível e exige 14 dias para síntese de novas enzimas antes de iniciar outro antidepressivo.';
      timelineSteps.push({stepNumber:1,periodLabel:'Dias 1 a 14',sourceDose:'SUSPENSA TOTALMENTE',targetDose:'NÃO INICIAR',clinicalAction:'Manter intervalo livre e restrição de tiramina.',symptomsToMonitor:'Retorno de sintomas.'},{stepNumber:2,periodLabel:'Dia 15 em diante',sourceDose:'SUSPENSA DEFINITIVAMENTE',targetDose:`${target.name} ${initialDose} mg/dia`,clinicalAction:'Iniciar na menor dose eficaz.',symptomsToMonitor:'Tolerabilidade e resposta.'});
    } else {
      durationWeeks=3; strategySummary='Troca envolvendo IMAO requer intervalo livre; validar janela específica pela farmacologia do par selecionado.';
      timelineSteps.push({stepNumber:1,periodLabel:'Fase de retirada',sourceDose:`Descontinuar ${source.name} de forma supervisionada`,targetDose:'NÃO INICIAR DURANTE SOBREPOSIÇÃO',clinicalAction:'Evitar sobreposição serotoninérgica.',symptomsToMonitor:'Sinais autonômicos e retorno de sintomas.'});
    }
  } else if(source.id==='fluoxetina'){
    strategyType='direct'; strategyTitle='Troca Direta Facilitada (Auto-Desmame pela Meia-Vida Longa)'; durationWeeks=2; strategySummary='A meia-vida longa da Fluoxetina/Norfluoxetina permite troca direta em muitos pares não-IMAO.';
    timelineSteps.push({stepNumber:1,periodLabel:'Semana 1',sourceDose:'SUSPENSA TOTALMENTE',targetDose:`${target.name} ${initialDose} mg/dia`,clinicalAction:`Suspender Fluoxetina e iniciar ${target.name} no dia seguinte.`,symptomsToMonitor:'Sobreposição serotoninérgica leve.'},{stepNumber:2,periodLabel:'Semana 2 em diante',sourceDose:'SUSPENSA DEFINITIVAMENTE',targetDose:`${target.name} ${targetDose} mg/dia`,clinicalAction:'Titular para dose alvo equivalente.',symptomsToMonitor:'Resposta clínica.'});
  } else if(source.class==='ISRS'&&target.class==='ISRS'&&sourceDoseMg<=source.hayasakaEqToFluoxetine40){
    strategyType='direct'; strategyTitle='Troca Direta'; durationWeeks=2; strategySummary='ISRS da mesma classe em dose baixa/média podem ser transicionados diretamente.';
    timelineSteps.push({stepNumber:1,periodLabel:'Semana 1',sourceDose:'SUSPENSA',targetDose:`${target.name} ${initialDose} mg/dia`,clinicalAction:`Interromper ${source.name} e iniciar ${target.name} no dia seguinte.`,symptomsToMonitor:'Sintomas gástricos ou cefaleia.'},{stepNumber:2,periodLabel:'Semana 2 em diante',sourceDose:'SUSPENSA DEFINITIVAMENTE',targetDose:`${target.name} ${targetDose} mg/dia`,clinicalAction:'Titular se tolerado.',symptomsToMonitor:'Eficácia clínica.'});
  } else {
    const half=Math.round(sourceDoseMg/2); strategySummary=`Reduzir progressivamente ${source.name} enquanto se introduz e titula ${target.name}.`;
    timelineSteps.push({stepNumber:1,periodLabel:'Semana 1',sourceDose:`${source.name} ${half} mg/dia`,targetDose:`${target.name} ${initialDose} mg/dia`,clinicalAction:'Reduzir 50% e iniciar alvo.',symptomsToMonitor:'Descontinuação e adaptação.'},{stepNumber:2,periodLabel:'Semana 2',sourceDose:sourceDoseMg>source.hayasakaEqToFluoxetine40?`${source.name} ${Math.round(half/2)} mg/dia (ou dias alternados)`:'SUSPENSA TOTALMENTE',targetDose:`${target.name} ${initialDose} a ${targetDose} mg/dia`,clinicalAction:'Suspender/reduzir mais e progredir alvo.',symptomsToMonitor:'Tolerabilidade e sono.'},{stepNumber:3,periodLabel:'Semana 3 em diante',sourceDose:'SUSPENSA DEFINITIVAMENTE',targetDose:`${target.name} ${targetDose} mg/dia`,clinicalAction:'Estabilizar na dose alvo.',symptomsToMonitor:'Resposta após 4 a 6 semanas de dose plena.'});
  }
  const pharmacologicalRationale=[`Meia-vida: ${source.name} (${source.halfLifeHours}) vs ${target.name} (${target.halfLifeHours}).`,`Potencial de Descontinuação: ${source.discontinuationRisk}.`,`Equivalência calculada: ${source.name} ${sourceDoseMg} mg/dia ≈ ${target.name} ~${raw.toFixed(1)} mg/dia; dose comercial mais próxima ${targetDose} mg/dia.`];
  const cypInteractions:string[]=[]; if((source.cypInteractions.cyp2D6||'').includes('Potente')||(source.cypInteractions.cyp2D6||'').includes('Moderado')) cypInteractions.push(`${source.name} apresenta inibição relevante de CYP2D6; considerar interação durante a transição.`); if((source.cypInteractions.cyp1A2||'').includes('Potente')) cypInteractions.push(`${source.name} é inibidor potente de CYP1A2.`);
  let serotoninRisk:'Baixo'|'Moderado'|'Alto'|'Crítico'='Moderado'; let serotoninNote='Risco padrão de sobreposição serotoninérgica; orientar sinais de alerta.'; if(source.class==='IMAO'||target.class==='IMAO'){serotoninRisk='Crítico';serotoninNote='PERIGO FATAL: IMAO com fármaco serotoninérgico pode precipitar síndrome serotoninérgica; intervalo livre é obrigatório.';}
  let discontinuationRisk=source.discontinuationRisk; let discontinuationNote='Monitorar síndrome FINISH.'; if(source.id==='paroxetina'||source.id==='venlafaxina'){discontinuationRisk='Muito Alto';discontinuationNote=`${source.name} possui alto risco de descontinuação; desacelerar o desmame se sintomas intensos.`;}
  const cardiacAndOtherAlerts:string[]=[]; if(target.id==='citalopram'||target.id==='escitalopram') cardiacAndOtherAlerts.push('Atenção ao QTc e limites de dose, especialmente em idosos.'); if(target.class==='Tricíclico') cardiacAndOtherAlerts.push('Tricíclicos: considerar ECG prévio em idosos/cardiopatas pelo risco de condução/arritmia.'); if(target.id==='venlafaxina'||target.id==='desvenlafaxina') cardiacAndOtherAlerts.push('Monitorar pressão arterial sistêmica.');
  const patientInstructions=[`Siga exatamente o cronograma indicado. Nunca interrompa bruscamente ${source.name}.`,'Procure a equipe se houver sintomas intensos de descontinuação.','Atendimento imediato se febre alta, tremores intensos, rigidez muscular ou confusão súbita.','Evite álcool e não inicie fitoterápicos/antigripais sem orientação.'];
  const soapSteps=timelineSteps.map(s=>`• ${s.periodLabel}: [Desmame] ${s.sourceDose} + [Introdução] ${s.targetDose}`).join('\n');
  const soapPrescriptionText=`PLANO DE TRANSIÇÃO E DESMAME DE ANTIDEPRESSIVO (${strategyTitle}):\nMedicação Atual: ${source.name} ${sourceDoseMg} mg/dia -> Nova Medicação: ${target.name} (Dose Alvo Estimada: ${targetDose} mg/dia)\nFonte de Equivalência: ${evidenceSource}\n\nCRONOGRAMA SEMANAL:\n${soapSteps}\n\nOrientações: Paciente orientado sobre sintomas transitórios de descontinuação e sinais de alerta. Retorno pactuado em 3 a 4 semanas.`;
  return {sourceDrug:source,sourceDoseMg,targetDrug:target,calculatedEquivalentDoseMg:raw,recommendedStartingDoseMg:initialDose,recommendedTargetDoseMg:targetDose,evidenceSource,strategyType,strategyTitle,strategySummary,durationWeeks,timelineSteps,pharmacologicalRationale,clinicalRisks:{serotoninSyndrome:{risk:serotoninRisk,note:serotoninNote},discontinuationSyndrome:{risk:discontinuationRisk,note:discontinuationNote},cypInteractions,cardiacAndOtherAlerts},patientInstructions,soapPrescriptionText};
}

export const EQUIVALENCE_REFERENCE_TABLE = Object.values(ANTIDEPRESSANTS_DB).map((drug)=>({ drug:drug.name, class:drug.class, dose40Eq:drug.hayasakaEqToFluoxetine40, dose20Eq:drug.hayasakaEqToFluoxetine40/2, isRct:drug.isRctEvidence, halfLife:drug.halfLifeHours }));
